name: usque
description: "A native, unofficial Consumer WARP client powered by Rust."
publish_to: 'none'
version: 0.3.1+25

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  lucide_icons_flutter:
    path: ../../third_party/lucide_icons_flutter-3.1.19
  flutter_svg: 2.3.0
  shared_preferences: ^2.5.5
  shared_preferences_platform_interface: 2.4.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/usque-ui-icon.png
    - assets/branding/usque-ui-icon-dark.png
    - assets/licenses/vpngate.txt
    - assets/licenses/boringtun.txt
    - assets/licenses/wgcf.txt
    - assets/icons/openvpn.svg
    - assets/icons/wireguard.svg
    - assets/icons/warp-wireguard.svg
    - assets/licenses/flagpedia.txt
    - assets/flags/w80/
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexMono-Medium.ttf
          weight: 500
