"""Generate public diagnostic allowlists from the shared, append-only contract."""

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACT = ROOT / "proto/usque/diagnostics-contract.json"
NAMES = {
    "check_ids": "checkIds",
    "event_types": "eventTypes",
    "failure_codes": "failureCodes",
    "summary_keys": "summaryKeys",
    "remediation_keys": "remediationKeys",
    "evidence_tokens": "evidenceTokens",
    "evidence_keys": "evidenceKeys",
    "log_event_codes": "logEventCodes",
}
OUTPUTS = {
    "rust": ROOT / "crates/usque-core/src/diagnostics_contract_generated.rs",
    "kotlin": ROOT
    / "apps/usque_gui/android/app/src/main/kotlin/io/github/georgexie2333/usque/DiagnosticsContract.kt",
    "dart": ROOT / "apps/usque_gui/lib/core/diagnostics_contract_generated.dart",
}


def validate(contract):
    """Reject unsafe public identifiers and inconsistent check dependencies."""
    if contract.get("schema_version") != 1:
        raise ValueError("unsupported diagnostic contract version")
    checks = contract["checks"]
    ids = [check["id"] for check in checks]
    if len(ids) != len(set(ids)):
        raise ValueError("duplicate diagnostic check")
    lists = {"check_ids": ids}
    lists.update({key: contract[key] for key in NAMES if key != "check_ids"})
    for key, values in lists.items():
        if not values or len(values) != len(set(values)):
            raise ValueError(f"empty or duplicate identifiers: {key}")
        if any(not re.fullmatch(r"[A-Za-z][A-Za-z0-9_.]*", value) for value in values):
            raise ValueError(f"unsafe identifiers: {key}")
    categories = {
        "LocalComponent",
        "PhysicalNetwork",
        "Transport",
        "Tunnel",
        "Protection",
        "Recovery",
    }
    for check in checks:
        if check["category"] not in categories or check["mode"] not in {"standard", "deep"}:
            raise ValueError("invalid diagnostic check metadata")
        for key in ("resource_group", "kind"):
            if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_]*", check[key]):
                raise ValueError("unsafe diagnostic check metadata")
        if any(dependency not in ids for dependency in check["dependencies"]):
            raise ValueError("missing diagnostic dependency")
    visiting, visited = set(), set()
    dependencies = {check["id"]: check["dependencies"] for check in checks}

    def visit(ident):
        if ident in visiting:
            raise ValueError("cyclic diagnostic dependencies")
        if ident in visited:
            return
        visiting.add(ident)
        for dependency in dependencies[ident]:
            visit(dependency)
        visiting.remove(ident)
        visited.add(ident)

    for ident in ids:
        visit(ident)
    return lists


def render(contract):
    lists = validate(contract)
    notice = "Generated by tool/generate_diagnostics_contract.py; edit the shared JSON contract."
    rust = [f"// {notice}", ""]
    rust += [
        "pub struct DiagnosticCheckDefinition {",
        "    pub id: &'static str,",
        "    pub category: &'static str,",
        "    pub dependencies: &'static [&'static str],",
        "    pub mode: &'static str,",
        "    pub resource_group: &'static str,",
        "    pub kind: &'static str,",
        "}",
        "",
        "pub const CHECK_DEFINITIONS: &[DiagnosticCheckDefinition] = &[",
    ]
    for check in contract["checks"]:
        rust += ["    DiagnosticCheckDefinition {"]
        for key in ("id", "category", "dependencies", "mode", "resource_group", "kind"):
            if key == "dependencies":
                values = ", ".join(f'"{value}"' for value in check[key])
                rust.append(f"        dependencies: &[{values}],")
            else:
                rust.append(f'        {key}: "{check[key]}",')
        rust += ["    },"]
    rust += ["];", ""]
    kotlin = [
        "package io.github.georgexie2333.usque",
        "",
        f"// {notice}",
        "internal object DiagnosticsContract {",
    ]
    dart = [f"// {notice}", "", "abstract final class DiagnosticsContract {"]
    for key, camel in NAMES.items():
        values = sorted(lists[key])
        rust += [f"pub const {key.upper()}: &[&str] = &["]
        rust += [f'    "{value}",' for value in values]
        rust += ["];", ""]
        kotlin += [f"    val {camel} =", "        setOf("]
        kotlin += [f'            "{value}",' for value in values]
        kotlin += ["        )"]
        dart += [f"  static const {camel} = <String>{{"]
        dart += [f"    '{value}'," for value in values]
        dart += ["  };", ""]
    kotlin += ["}"]
    dart = dart[:-1] + ["}"]
    return {
        "rust": "\n".join(rust),
        "kotlin": "\n".join(kotlin) + "\n",
        "dart": "\n".join(dart) + "\n",
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    contract = json.loads(CONTRACT.read_text(encoding="utf-8"))
    stale = []
    for language, contents in render(contract).items():
        path = OUTPUTS[language]
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != contents:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(contents, encoding="utf-8", newline="\n")
    if stale:
        parser.exit(1, "Stale diagnostic projections: " + ", ".join(stale) + "\n")
    print("DIAGNOSTICS_CONTRACT_OK")


if __name__ == "__main__":
    main()
