import 'app_strings.dart';

// Generation statuses and failures; shared actions use the main catalog.
const _keys = [
  'generate',
  'completed',
  'cancelled',
  'failed',
  'unavailable',
  'identity_required',
  'underlay_failed',
  'registration_failed',
];
const kWarpCatalogs = <String, List<String>>{
  'en': [
    'Generate WARP configuration',
    'Complete',
    'Cancelled',
    'Failed',
    'Check your WARP account and MASQUE connection, then retry.',
    "First select an account that has been set up.",
    "The temporary MASQUE connection could not be established. Check the outer connection settings.",
    "Cloudflare WARP registration failed. The code below identifies the failed stage.",
  ],
  'zh_CN': [
    '生成 WARP 配置',
    '已完成',
    '已取消',
    '失败',
    '请检查 WARP 账号和 MASQUE 连接后重试。',
    "请先选择一个已完成设置的账号。",
    "无法建立临时 MASQUE 连接，请检查外层连接设置。",
    "Cloudflare WARP 注册失败，下方错误码标明失败阶段。",
  ],
  'zh_HK': [
    '產生 WARP 設定',
    '已完成',
    '已取消',
    '失敗',
    '請檢查 WARP 帳戶和 MASQUE 連線後重試。',
    "請先選擇已完成設定的帳戶。",
    "無法建立臨時 MASQUE 連線，請檢查外層連線設定。",
    "Cloudflare WARP 註冊失敗，下方錯誤碼標明失敗階段。",
  ],
  'zh_TW': [
    '產生 WARP 設定',
    '已完成',
    '已取消',
    '失敗',
    '請檢查 WARP 帳號和 MASQUE 連線後重試。',
    "請先選擇已完成設定的帳號。",
    "無法建立暫時的 MASQUE 連線，請檢查外層連線設定。",
    "Cloudflare WARP 註冊失敗，下方錯誤碼標示失敗階段。",
  ],
  'ja': [
    'WARP 設定を生成',
    '完了',
    'キャンセル済み',
    '失敗',
    'WARP アカウントと MASQUE 接続を確認して再試行してください。',
    "先に設定済みのアカウントを選択してください。",
    "一時的な MASQUE 接続を確立できません。外側の接続設定を確認してください。",
    "Cloudflare WARP の登録に失敗しました。下のコードで失敗した段階を確認できます。",
  ],
  'ko': [
    'WARP 구성 생성',
    '완료',
    '취소됨',
    '실패',
    'WARP 계정과 MASQUE 연결을 확인하고 다시 시도하세요.',
    "먼저 설정이 완료된 계정을 선택하세요.",
    "임시 MASQUE 연결을 설정할 수 없습니다. 외부 연결 설정을 확인하세요.",
    "Cloudflare WARP 등록에 실패했습니다. 아래 코드는 실패한 단계를 나타냅니다.",
  ],
  'de': [
    'WARP-Konfiguration erstellen',
    'Abgeschlossen',
    'Abgebrochen',
    'Fehlgeschlagen',
    'WARP-Konto und MASQUE-Verbindung prüfen und erneut versuchen.',
    "Wählen Sie zuerst ein eingerichtetes Konto.",
    "Die temporäre MASQUE-Verbindung konnte nicht hergestellt werden. Prüfe die Einstellungen der äußeren Verbindung.",
    "Die Cloudflare-WARP-Registrierung ist fehlgeschlagen. Der folgende Code zeigt den betroffenen Schritt.",
  ],
  'fr': [
    'Créer une configuration WARP',
    'Terminé',
    'Annulé',
    'Échec',
    'Vérifiez votre compte WARP et la connexion MASQUE, puis réessayez.',
    "Sélectionnez d’abord un compte configuré.",
    "Impossible d’établir la connexion MASQUE temporaire. Vérifiez les paramètres de la connexion externe.",
    "L’inscription Cloudflare WARP a échoué. Le code ci-dessous indique l’étape en échec.",
  ],
  'es': [
    'Generar configuración WARP',
    'Completado',
    'Cancelado',
    'Error',
    'Comprueba la cuenta WARP y la conexión MASQUE e inténtalo de nuevo.',
    "Primero selecciona una cuenta ya configurada.",
    "No se pudo establecer la conexión MASQUE temporal. Revisa la configuración de la conexión externa.",
    "Falló el registro de Cloudflare WARP. El código siguiente indica la etapa que falló.",
  ],
  'pt': [
    'Gerar configuração WARP',
    'Concluído',
    'Cancelado',
    'Falhou',
    'Verifique a conta WARP e a ligação MASQUE e tente novamente.',
    "Primeiro selecione uma conta já configurada.",
    "Não foi possível estabelecer a conexão MASQUE temporária. Verifique as configurações da conexão externa.",
    "O registro do Cloudflare WARP falhou. O código abaixo indica a etapa que falhou.",
  ],
  'nl': [
    'WARP-configuratie maken',
    'Voltooid',
    'Geannuleerd',
    'Mislukt',
    'Controleer uw WARP-account en MASQUE-verbinding en probeer opnieuw.',
    "Selecteer eerst een ingesteld account.",
    "De tijdelijke MASQUE-verbinding kon niet worden gemaakt. Controleer de instellingen van de buitenste verbinding.",
    "Cloudflare WARP-registratie is mislukt. De onderstaande code geeft de mislukte stap aan.",
  ],
  'it': [
    'Genera configurazione WARP',
    'Completato',
    'Annullato',
    'Non riuscito',
    'Controlla account WARP e connessione MASQUE, poi riprova.',
    "Seleziona prima un account già configurato.",
    "Impossibile stabilire la connessione MASQUE temporanea. Controlla le impostazioni della connessione esterna.",
    "La registrazione Cloudflare WARP non è riuscita. Il codice seguente indica la fase non riuscita.",
  ],
  'ru': [
    'Создать конфигурацию WARP',
    'Завершено',
    'Отменено',
    'Ошибка',
    'Проверьте аккаунт WARP и соединение MASQUE и повторите попытку.',
    "Сначала выберите настроенный аккаунт.",
    "Не удалось установить временное соединение MASQUE. Проверьте настройки внешнего соединения.",
    "Регистрация Cloudflare WARP не удалась. Код ниже указывает этап сбоя.",
  ],
  'uk': [
    'Створити конфігурацію WARP',
    'Завершено',
    'Скасовано',
    'Помилка',
    'Перевірте обліковий запис WARP і з’єднання MASQUE та спробуйте знову.',
    "Спочатку виберіть налаштований обліковий запис.",
    "Не вдалося встановити тимчасове з’єднання MASQUE. Перевірте налаштування зовнішнього з’єднання.",
    "Реєстрація Cloudflare WARP не вдалася. Код нижче вказує етап збою.",
  ],
  'pl': [
    'Utwórz konfigurację WARP',
    'Ukończono',
    'Anulowano',
    'Błąd',
    'Sprawdź konto WARP i połączenie MASQUE, a następnie ponów próbę.',
    "Najpierw wybierz skonfigurowane konto.",
    "Nie można nawiązać tymczasowego połączenia MASQUE. Sprawdź ustawienia połączenia zewnętrznego.",
    "Rejestracja Cloudflare WARP nie powiodła się. Poniższy kod wskazuje etap błędu.",
  ],
  'tr': [
    'WARP yapılandırması oluştur',
    'Tamamlandı',
    'İptal edildi',
    'Başarısız',
    'WARP hesabını ve MASQUE bağlantısını kontrol edip yeniden deneyin.',
    "Önce kurulumu tamamlanmış bir hesap seçin.",
    "Geçici MASQUE bağlantısı kurulamadı. Dış bağlantı ayarlarını kontrol edin.",
    "Cloudflare WARP kaydı başarısız oldu. Aşağıdaki kod başarısız aşamayı gösterir.",
  ],
  'id': [
    'Buat konfigurasi WARP',
    'Selesai',
    'Dibatalkan',
    'Gagal',
    'Periksa akun WARP dan koneksi MASQUE, lalu coba lagi.',
    "Pilih dulu akun yang sudah disiapkan.",
    "Koneksi MASQUE sementara tidak dapat dibuat. Periksa pengaturan koneksi luar.",
    "Pendaftaran Cloudflare WARP gagal. Kode di bawah menunjukkan tahap yang gagal.",
  ],
  'vi': [
    'Tạo cấu hình WARP',
    'Hoàn tất',
    'Đã hủy',
    'Thất bại',
    'Kiểm tra tài khoản WARP và kết nối MASQUE rồi thử lại.',
    "Trước tiên, hãy chọn một tài khoản đã được thiết lập.",
    "Không thể thiết lập kết nối MASQUE tạm thời. Hãy kiểm tra cài đặt kết nối ngoài.",
    "Đăng ký Cloudflare WARP thất bại. Mã bên dưới cho biết bước gặp lỗi.",
  ],
  'th': [
    'สร้างการตั้งค่า WARP',
    'เสร็จสิ้น',
    'ยกเลิกแล้ว',
    'ล้มเหลว',
    'ตรวจสอบบัญชี WARP และการเชื่อมต่อ MASQUE แล้วลองอีกครั้ง',
    "เลือกบัญชีที่ตั้งค่าแล้วก่อน",
    "ไม่สามารถสร้างการเชื่อมต่อ MASQUE ชั่วคราวได้ โปรดตรวจสอบการตั้งค่าการเชื่อมต่อภายนอก",
    "ลงทะเบียน Cloudflare WARP ไม่สำเร็จ รหัสด้านล่างระบุขั้นตอนที่ล้มเหลว",
  ],
  'ar': [
    'إنشاء إعداد WARP',
    'مكتمل',
    'ملغى',
    'فشل',
    'تحقق من حساب WARP واتصال MASQUE ثم أعد المحاولة.',
    "اختر أولًا حسابًا تم إعداده.",
    "تعذر إنشاء اتصال MASQUE المؤقت. تحقق من إعدادات الاتصال الخارجي.",
    "فشل تسجيل Cloudflare WARP. يحدد الرمز أدناه المرحلة التي فشلت.",
  ],
  'fa': [
    'ساخت پیکربندی WARP',
    'تکمیل شد',
    'لغو شد',
    'ناموفق',
    'حساب WARP و اتصال MASQUE را بررسی و دوباره تلاش کنید.',
    "ابتدا یک حساب راه‌اندازی‌شده انتخاب کنید.",
    "اتصال موقت MASQUE برقرار نشد. تنظیمات اتصال بیرونی را بررسی کنید.",
    "ثبت‌نام Cloudflare WARP ناموفق بود. کد زیر مرحلهٔ خطا را مشخص می‌کند.",
  ],
};

extension WarpStrings on AppStrings {
  String warp(String key) {
    final index = _keys.indexOf(key);
    if (index < 0) return key;
    return (kWarpCatalogs[catalogId] ?? kWarpCatalogs['en']!)[index];
  }
}
